require_relative "test_layout"
require_relative "test_space"
require_relative "test_object"
require_relative "test_list"
require_relative "test_word"
require_relative "test_dictionary"
require_relative "test_method"
require_relative "test_attributes"
