
require_relative "test_basic"
require_relative "test_compound"
require_relative "test_arguments"
require_relative "test_expressions"
require_relative "test_function_call"
require_relative "test_conditional"
require_relative "test_while"
require_relative "test_operators"
require_relative "test_function_definition"
require_relative "test_root"