require "parfait/value"
require "parfait/object"
require "parfait/module"
require "parfait/class"
require "parfait/method"
require "parfait/dictionary"
require "parfait/list"
require "parfait/layout"
require "parfait/word"
require "parfait/message"
require "parfait/frame"
require "parfait/space"

#if we are in the ruby run-time / generating an executable
require "virtual/parfait_adapter"
