require "rx-file"

require_relative "util"
require_relative "elf/object_writer"
require_relative "risc"
require_relative "slot_machine/slot_machine"
require_relative "slot_language/slot_compiler"
require_relative "arm/arm_machine"
require_relative "arm/arm_platform"
require_relative "sol/statement"
require_relative "sol/builtin"
require_relative "ruby"
require_relative "rubyx/rubyx_compiler"
