require_relative "test_adds"
require_relative "test_calls"
require_relative "test_hello"
require_relative "test_itos"
require_relative "test_loop"

require_relative "test_many_adds"
require_relative "test_many_hello"
require_relative "test_many_calls"
require_relative "test_many_itos"
