require_relative "test_add"
require_relative "test_change"
require_relative "test_if"
require_relative "test_puts"
require_relative "test_plus"
require_relative "test_mult"
require_relative "test_word"
